services:
  - type: web
    name: telao-igreja-backend
    runtime: node
    plan: free

    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/server/index.js

    healthCheckPath: /api/health

    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: REFRESH_SECRET
        generateValue: true

      - key: ALLOWED_ORIGINS
        value: "*"

      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_USERNAME
        sync: false
